### ISSUE TITLE
[Mosaic] deprecation notice from jotai

### ISSUE THREAD

**Issue by robbieaverill** [stoplightio/json-schema-viewer#259]
## Context
The browser console is full of deprecation notices when using json-schema-viewer. I would love to help upgrade this dependency, however it seems like Mosaic is not an open source library.

## Current Behavior
* Load a page using json-schema-viewer
* Open browser console
* Notice many deprecation notices

```
console.js:273 [DEPRECATED]: use `useAtomValue` from `jotai` instead. 
    at Divider (webpack-internal:///../../common/temp/node_modules/.pnpm/@stoplight+json-schema-viewer@4.16.1_@babel+core@7.23.7_@babel+template@7.24.7_@stoplight+mar_5xf4cu4e5qhaddtsd35lb2ujpe/node_modules/@stoplight/json-schema-viewer/index.mjs:787:20)
    at div
    at Box (webpack-internal:///../../common/temp/node_modules/.pnpm/@stoplight+mosaic@1.53.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@stoplight/mosaic/core.esm.js:759:3)
    at Flex (webpack-internal:///../../common/temp/node_modules/.pnpm/@stoplight+mosaic@1.53.2_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@stoplight/mosaic/core.esm.js:6125:3)
    at div
```

## Expected Behavior
* Deprecation notices are addressed and longer exist

## Possible Workaround/Solution
N/A

- Version used: json-schema-viewer 4.16.1, mosaic 1.53.2
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 126, Node 20
- Operating System and version (desktop or mobile): desktop
- Link to your environment/workspace/project: N/A

**Comment by weyert** [comment]
Fixed some of it as part of https://github.com/stoplightio/json-schema-viewer/pull/260
